# Generated by Django 4.2 on 2023-04-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=15)),
                ('exp', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
